### ISSUE TITLE
Ruby remote debugging/variable inspection does not work with Byebug >= 9.0.0

### ISSUE THREAD

**Issue by blfgomes** [Komodo/KomodoEdit#1709]
### Short Summary
When remote debugging a Ruby program, variable inspection is broken.

### Steps to Reproduce
Start a remote debugger session (see https://github.com/Komodo/KomodoEdit/issues/1708) and try to inspect a local variable or explicitly watch a variable.

### Expected results
The variable's value should be shown.

### Actual results
There is a string with the exception "undefined method local_variable_get" instead of the variable's value.

### Platform Information

*Komodo IDE 10.0* 
*Red Hat Enterprise Linux Server release 7.2 (Maipo)*
*ruby 2.0.0p598 (2014-11-13) [x86_64-linux]*

### Additional Information

When explicitly installing Byebug 8.2.5, variable inspection works as expected.

**Comment by cgchoffman** [comment]
> When explicitly installing Byebug 8.2.5, variable inspection works as expected.

What version is breaking for you? I assume it's "the latest" but that has a tendency to change meaning as time passes.

**Comment by cgchoffman** [comment]
I also don't want to make an @$$ of either one of us...

**Comment by blfgomes** [comment]
I can say for sure that 9.0.0 and 9.0.5 breaks it, so it's safe to assume that 9.0.0 introduced the changes that broke it.
The latest version today is 9.0.5.

More info on the exception:
<![CDATA[undefined method `local_variable_get' for #<Binding:0x0000000089ccb8>
["/usr/local/share/gems/gems/byebug-9.0.0/lib/byebug/frame.rb:57:in `block in locals'", "/usr/local/share/gems/gems/byebug-9.0.0/lib/byebug/frame.rb:56:in `each'", "/usr/local/share/gems/gems/byebug-9.0.0/lib/byebug/frame.rb:56:in `each_with_object'", "/usr/local/share/gems/gems/byebug-9.0.0/lib/byebug/frame.rb:56:in `locals'", "/rhome/bruno/Komodo-RubyRemoteDebugging-10.0.0-89159-linux-x86_64/rdbgp2.rb:1336:in `get_properties'", "/rhome/bruno/Komodo-RubyRemoteDebugging-10.0.0-89159-linux-x86_64/rdbgp2.rb:1437:in `get_property'", "/rhome/bruno/Komodo-RubyRemoteDebugging-10.0.0-89159-linux-x86_64/rdbgp2.rb:1480:in `on_property_get'", "/rhome/bruno/Komodo-RubyRemoteDebugging-10.0.0-89159-linux-x86_64/rdbgp2.rb:767:in `block in run_cmd'", "/usr/local/share/gems/gems/byebug-9.0.0/lib/byebug/processors/command_processor.rb:169:in `safely'", "/rhome/bruno/Komodo-RubyRemoteDebugging-10.0.0-89159-linux-x86_64/rdbgp2.rb:746:in `run_cmd'", "/usr/local/share/gems/gems/byebug-9.0.0/lib/byebug/processors/command_processor.rb:149:in `repl'", "/usr/local/share/gems/gems/byebug-9.0.0/lib/byebug/processors/command_processor.rb:98:in `process_commands'", "/rhome/bruno/Komodo-RubyRemoteDebugging-10.0.0-89159-linux-x86_64/rdbgp2.rb:665:in `at_line'", "/usr/local/share/gems/gems/byebug-9.0.0/lib/byebug/context.rb:96:in `at_line'", "yaml.rb:7:in `<main>'"]]]>

**Comment by mitchell-as** [comment]
This is interesting.

I see you are using Ruby 2.0.0. The new Byebug-based Ruby 2 debug client was developed for Ruby 2.1+ because that is what Byebug supported at the time. It appears Byebug 9.0 introduced support for Ruby 2.0.0.

Komodo's original Ruby debugger was designed to work with Ruby 1.8-2.0.0 (no higher). You may have more success with that. (Right now we support both -- just start your remote debug session with the old instructions that do not make use of `rdbgp2.rb`.)

I hope that eventually we'll be able to support 2.0.0 debugging with newer versions of Byebug, so I'll leave this ticket open while I investigate.

**Comment by blfgomes** [comment]
Looking at the changelog for Byebug 9.0.0, I can see that support for Ruby 2.0.0 was actually *removed*:

> ## Removed
> 
> Official Ruby 2.0.0

https://github.com/deivid-rodriguez/byebug/releases/tag/v9.0.0

If that's the case, there is nothing you can do on your end except noting that on the documentation: rdbgp2.rb debugging is only supported for Ruby 2.1+ *or* Ruby 2.0.0 should use Byebug 8.2.5 (that seems to be working for me). 

I'll try to see if remote debugging with rdbgp2.rb works with Ruby 2.1+ and Byebug 9.0+ just to make sure that's the only problem.

**Comment by mitchell-as** [comment]
Oh goodness, thanks for the catch!

**Comment by mitchell-as** [comment]
Note to self: update the documentation to explicitly state the new Ruby 2 debugger does not support 2.0.0 for Byebug >= 9.0. Use 8.2.5 for 2.0.0.

**Comment by Naatan** [comment]
@mitchell-as why did Komodo try to debug Ruby 2.0 with Byebug though? That seems like a bug.

**Comment by mitchell-as** [comment]
The OP stated a remote debug session was started with our Byebug version. It wasn't local.

**Comment by mitchell-as** [comment]
Updated the FAQ (http://docs.komodoide.com/Manual/trouble#ruby_debug_x64) to state Ruby 2.1+ uses Byebug, while Ruby 2.0 uses libraries we ship with Komodo. I'm not mentioning that previous versions of Byebug work with Ruby 2.0 because our new Ruby debugger was targeted at Ruby 2.1+. The previous "2.x" claim was inaccurate.

Also updated the Ruby Debug page (http://docs.komodoide.com/Manual/debugruby) to explicitly state that `rdbgp.rb` is used for Ruby 1.8-2.0 and `rdbgp2.rb` is used for Ruby 2.1+.
