### ISSUE TITLE
Komodo IDE 10 Spellchecker Consistently Fails

### ISSUE THREAD

**Issue by jonathaneunice** [Komodo/KomodoEdit#2161]
### Short Summary

Komodo IDE 10 spellchecker dies, apparently every time it attempts to run. Help > Troubleshooting > View Log File shows a stream of errors of the form:

TypeError: w.require(...).checkSpelling is not a function

This is on a system where spell checking works fine in Komodo IDE 9. The dictionary files are in place for IDE 10, and the IDE is otherwise working fine. I have tried re-installing the software, with identical results. I have 
tried Help > Check for Updates and there are no updates available.

### Steps to Reproduce

Run Komodo IDE 10. Load file that would be spellchecked. Note errors in log.

### Expected results

Spellchecker to run, highlight probably misspelled words.

### Actual results

No spellcheck highlighting. Raft of errors in log.

### Platform Information

Mac OS X 10.11.6 (15G31)

*Komodo Edit or IDE?* 

IDE

commercially licensed, and program properly cites license info

*Komodo Version?* 

Komodo IDE, version 10.1.1, build 89474, platform macosx.
Built on Thu Sep 1 15:11:44 2016.

*Operating System (and version)?* 

Mac OS X 10.11.6 (15G31)

### Additional Information

Log:

[2016-11-18 12:04:24,952] [ERROR] console-logger: TypeError: w.require(...).checkSpelling is not a function (2) in viewbufferbase:1139
Traceback (most recent call last):
  File "viewbufferbase", line 1139, in 

[2016-11-18 12:04:26,551] [ERROR] console-logger: TypeError: w.require(...).checkSpelling is not a function (2) in viewbufferbase:1139
Traceback (most recent call last):
  File "viewbufferbase", line 1139, in 

[2016-11-18 12:04:28,153] [ERROR] console-logger: TypeError: w.require(...).checkSpelling is not a function (2) in viewbufferbase:1139
Traceback (most recent call last):
  File "viewbufferbase", line 1139, in 

[2016-11-18 12:04:29,752] [ERROR] console-logger: TypeError: w.require(...).checkSpelling is not a function (2) in viewbufferbase:1139
Traceback (most recent call last):
  File "viewbufferbase", line 1139, in 

... times infinite repeats

No workarounds found. Reinstall Komodo IDE from fresh download gives same results.

**Comment by Naatan** [comment]
This may be caused by a bug we found recently, please try this:

Open the console widget (bottom pane) and execute the following:

```
require("ko/prefs").setBoolean('runGetStartedTutorial', false)
```

Then restart Komodo.

**Comment by jonathaneunice** [comment]
Sadly, no dice. The 'is not a function' metronome continues ticking.

I also tried setting it to `true`, and also `Help > Run First Start Wizard Again`. I tried resetting the color scheme and key bindings to default, and asked the First Start Wizard to run the tutorial again. All with extensive quit/restarts between appropriate steps. Nothing.

Possibly a clue: No such tutorial ever ran, even when I asked the First Start Wizard to run it.

**Comment by jonathaneunice** [comment]
A final attempt "Reset Everything" did solve the problem. At the cost of all my configurations. But at least spellchecking is back!

**Comment by Naatan** [comment]
Did you restart Komodo after executing the code snippet I shared?

**Comment by jonathaneunice** [comment]
Yes. That was the "no dice" comment above. Code snippet, execute in console, restart...no effect. 

I described other, related and quasi-related things I tried, also without effect. The only motion came when I did a Help > Troubleshooting > Reset Everything. The "nuclear option." 

I suspect some earlier config setting (many of which were imported when I upgraded from 9.x) caused code to break, leading to `checkSpelling()` not being properly hooked in.

**Comment by jonathaneunice** [comment]
I will provide any further information I can if you think this is a general problem, but for my own purposes I consider this a resolved issue, and will close the ticket.

**Comment by cgchoffman** [comment]
@jonathaneunice, you're thinking of forum posts.  We don't close these issues until they are fixed

**Comment by cgchoffman** [comment]
OH nvm, @Naatan agrees with you @jonathaneunice.  Closing this.

**Comment by simbabque** [comment]
I had the same error in Komodo IDE, version 10.1.4, build 89515, ticking every second. Going to Preferences > Syntax & Spell Checking > Spell Checking and unchecking everything helped. Since I never realized there was a spell checking (as it didn't work) I don't mind that it's off now.
