### ISSUE TITLE
Abbreviation not found in Komodo Edit, version 10.2.1

### ISSUE THREAD

**Issue by mistergraphx** [Komodo/KomodoEdit#2384]
### Short Summary

Hi,

Komodo abbreviations insertion not triggered, since last update 

I've associated all snippets with a language, checked the auto abbreviation option.

### Steps to Reproduce

I've tried, in Komodo Edit, version 10.2.0, build 17657, platform macosx. Built on Fri Feb 17 22:36:09 2017, the snippets insertion works as expected .

But not in the latest nightly

I've tried to restart without addons, same result.

The keyboard shortcut is set to meta+t
Snippets are stored in my tolbox > Abbreviations (which is not necessary since latest updates and work in 10.2.0, in any folders or sub-folders )

### Expected results

Trigger abbreviation insertion

### Actual results

no abbreviation found

### Platform Information

Komodo Edit, version 10.2.1, build 17665, platform macosx.
Built on Thu Mar 2 20:25:54 2017.

Mac OsX 10.9.5

### Additional Information

This is the log file, if it could help…
```
[2017-03-07 08:19:16,134] [INFO] Startup: Welcome to Komodo Edit 10.2.1 build 17665 (platform macosx, running on Darwin 13.4.0 version Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64)
[2017-03-07 08:19:16,135] [INFO] Startup: /Applications/KOMODO/Komodo Edit 10.nightly.app/Contents/MacOS/komodo built on Thu Mar 2 20:25:54 2017
[2017-03-07 08:19:16,316] [INFO] koInitService: installing Komodo samples to '/Users/macbook/Library/Application Support/KomodoEdit/10.2/samples'
[2017-03-07 08:19:16,567] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2017-03-07 08:19:17,339] [WARNING] koLess: Clearing local and file cache
[2017-03-07 08:19:17,481] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-03-07 08:19:18,961] [ERROR] window-bindings: 
-- EXCEPTION START --
TypeError: w.require is not a function
+ stack
    root-element_XBL_Constructor@chrome://komodo/content/bindings/windows.xml:31:17
-- EXCEPTION END --
[2017-03-07 08:19:19,087] [WARNING] console-logger: Expected identifier for pseudo-class or pseudo-element but found ' '.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/codeintel.css:1
[2017-03-07 08:19:19,088] [WARNING] console-logger: Unexpected end of file while searching for closing } of invalid rule set. (1) in chrome://komodo/skin/codeintel.css:42
[2017-03-07 08:19:19,172] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2017-03-07 08:19:20,797] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2017-03-07 08:19:21,689] [DEBUG] console: log: {}
[2017-03-07 08:19:21,899] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-03-07 08:19:21,942] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-03-07 08:19:22,371] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/KOMODO/Komodo%20Edit%2010.nightly.app/Contents/Resources/components/koamAddonManager.js:138
[2017-03-07 08:19:22,751] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/KOMODO/Komodo%20Edit%2010.nightly.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/KOMODO/Komodo%20Edit%2010.nightly.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2017-03-07 08:19:22,757] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/KOMODO/Komodo%20Edit%2010.nightly.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/KOMODO/Komodo%20Edit%2010.nightly.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2017-03-07 08:19:25,819] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2017-03-07 08:19:25,819] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2017-03-07 08:19:25,819] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2017-03-07 08:19:25,819] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2017-03-07 08:19:25,820] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2017-03-07 08:19:25,821] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2017-03-07 08:19:25,821] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2017-03-07 08:19:25,822] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2017-03-07 08:19:25,874] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-03-07 08:19:25,882] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
ERROR:xpcom:Creation of class '<class 'component:koCommandmentService.KoCommandmentService'>' failed!
Exception details follow

ERROR:xpcom:Unhandled exception calling 'int8 * createInstance(in nsISomething, in nsIID &, out retval InterfaceIs *);'
Traceback (most recent call last):
  File "/Applications/KOMODO/Komodo Edit 10.nightly.app/Contents/Resources/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/Applications/KOMODO/Komodo Edit 10.nightly.app/Contents/Resources/python/xpcom/server/factory.py", line 57, in createInstance
    return self.klass()
  File "/Applications/KOMODO/Komodo Edit 10.nightly.app/Contents/Resources/components/koCommandmentService.py", line 477, in __init__
    self._reader = _CommandmentsReader(koDirs.userDataDir, ver)
  File "/Applications/KOMODO/Komodo Edit 10.nightly.app/Contents/Resources/components/koCommandmentService.py", line 386, in __init__
    self._pipe = os.open(self._commandmentsFileName, os.O_RDWR)
OSError: [Errno 2] No such file or directory: '/Users/macbook/Library/Application Support/KomodoEdit/10.2/commandments.fifo'
[2017-03-07 08:19:25,887] [ERROR] koInitService: Unable to start 'koCommandmentService' service: '@activestate.com/koCommandmentService;1'
Traceback (most recent call last):
  File "/Applications/KOMODO/Komodo Edit 10.nightly.app/Contents/Resources/components/koInitService.py", line 406, in loadStartupCategories
    getService(components.interfaces.nsIObserver)
  File "/Applications/KOMODO/Komodo Edit 10.nightly.app/Contents/Resources/python/xpcom/components.py", line 195, in getService
    return serviceManager.getServiceByContractID(self.contractid, _get_good_iid(iid))
  File "<XPCOMObject method 'getServiceByContractID'>", line 3, in getServiceByContractID
Exception: 2147500037 (NS_ERROR_FAILURE)
[2017-03-07 08:19:44,383] [WARNING] views: Inconsistent view count in view_closed event
```

**Comment by Naatan** [comment]
Could you share a snippet that is failing to trigger? And please add exact steps to reproduce. Meaning your step by step process for triggering the snippet.

**Comment by mistergraphx** [comment]
Yes, here is an example scss snippet (they all do the same result)

[example_scss_snippet.zip](https://github.com/Komodo/KomodoEdit/files/824899/example_scss_snippet.zip)

Here is a screen capture of the editor window, when i triggered the abbreviation insert with <kbd>meta+t</kbd> keyboard shortcut

![capture d ecran 2017-03-07 a 16 43 06](https://cloud.githubusercontent.com/assets/2979188/23664206/346b0a56-0355-11e7-8db7-12ab50327d07.png)

i've not tried to reset komodo prefs, to see if it solve the problem… let me know

Thanks for your answer, and work.

**Comment by cgchoffman** [comment]
Thanks for clarify the steps.  I'm guessing you've upgraded from Komodo 9 or 8?  Meta+T should open a new Tab View in Komodo.  A tab view is like what the Start Screen used to be in Komodo.  

Since you have the abbreviation set as "Auto-abbreviation" you can simply hit `Tab` and that will expand the snippet.  If you want the previous keybinding of `Cmd+T` to run `cmd_expandAbbrev` you can customize it in the *prefs > Keybindings*.

Let us know if that resolves the issue.

**Comment by mistergraphx** [comment]
It's already done.
![capture d ecran 2017-03-07 a 21 52 22](https://cloud.githubusercontent.com/assets/2979188/23677442/79e6cfb8-0380-11e7-8479-a03814bd9f28.png)

I use Komodo since Komodo Edit 5 ^^, but i use tab as trigger to Xemmet interpolations.
With all extensions disabled, i reproduce the same issue.

Tested with this build : Komodo Edit, version 10.2.0, build 17657, platform macosx.
Built on Fri Feb 17 22:36:09 2017.
it's ok.
![capture d ecran 2017-03-07 a 22 04 36](https://cloud.githubusercontent.com/assets/2979188/23677864/1c7b1f94-0382-11e7-888b-44b2e3afa5b2.png)

**Comment by cgchoffman** [comment]
@mistergraphx thanks for your patients and details.  It does look like there is a bug that cropped in here.  It's kind of a non-regression regression.  The way the `cmd_expandAbbrev` function was written it should never get abbreviations that have `auto-abbreviation` set to `true`.  This was not happening and people were always getting an abbreviation back regardless of that setting. Here's the code if you're interested: https://github.com/Komodo/Komodoedit/blob/master//src/chrome/komodo/content/library/abbrev.js#L232

I recently made changes to the toolbox to make things a little easier for us and users to maintain the toolbox.  I guess I've forced the function to worked "correctly".

I have a patch to fix the regression and bring back the functionality you were expecting.  I'm going to push but there are a couple of options for you so you don't have to wait:
- given your preferred tab setting, you can also have "space" expand an auto-abbrev by setting *Prefs > Editor > Smart Editing: Auto-Abbreviations* and add a space (" ", no quotes) to the trigger char field.
- disable auto-abbrev in the abbreviations you want to use using `Meta+T`

Hope that helps.

**Comment by mistergraphx** [comment]
> I recently made changes to the toolbox to make things a little easier for us and users to maintain the toolbox. I guess I've forced the function to worked "correctly".

I've read most of the discussions and commits about and it's great ;-) anyway there is always some side effects specially when using a pre-release version.

The tips you gived, solved the problem actually, thanks for your interest and work.
